### ISSUE TITLE
Implement output formatting from Draft 2019-09

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#100]
https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-10

It does seem like a good way to standardize error output, regardless of the used schema version.

- [x] [Flag](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-10.4.1)
- [x] [Basic](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-10.4.2)
- [ ] [Detailed](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-10.4.3)
- [ ] [Verbose](https://datatracker.ietf.org/doc/html/draft-handrews-json-schema-02#section-10.4.4)

**Comment by driv3r** [comment]
Hey @Stranger6667 ! I wanted to look into this issue, any up front pointers would be awesome.

**Comment by Stranger6667** [comment]
Hi @driv3r !

Thank you for taking a step :) My initial plan was:

- store paths inside validators (as `String` or `Vec<String>`, not sure which one is more convenient). So, each validator knows its location within the schema.
- have a pointer (`Vec<String>` - JSON Pointer chunks) to a part of data being validated. This one could not be necessary in all cases, as we often can derive it from the current validator path. Skipping it for such cases seems like optimization to me and can be done later. 
- If an error happens, then `ValidationError` might take the validator's path & pointer to the current data part
- Implement a function on `ErrorIterator` (probably requires making it a separate struct & implementing `IntoIterator` on it) that will take some kind of "format" enum value that will consume the iterator and transform those errors into the desired format.

Let me know if I can provide more info

**Comment by driv3r** [comment]
I assume we can get the path from the `Context.scope` I saw that it's available during validator compilation phase or should I look for something else?

**Comment by Stranger6667** [comment]
Partially - it only changes when sub-folders are involved (via `$id` / `id` keywords), but it can be changed to keep track of all steps! :)

Also, it might be a bit tricky when the scope changes to another document (e.g. a remote one in the `$ref` keyword implementation), so we need to have all chunks that will lead to the root document.

But I think it is the right direction indeed :)

**Comment by Stranger6667** [comment]
`flag` and `basic` styles were implemented via #274 

I'll put `detailed` & `verbose` to separate issues
