### ISSUE TITLE
Reduce compiled lib size

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#104]
Currently, for Python, we have ~8.5 Mb wheel, which is kinda a lot, but I think we can reduce it without sacrificing performance. Few ideas:

- Strip symbols (e.g. like `maturin` does with `--strip` option)
- Set codegen units to 1
- LTO optimization?

I am not completely sure what else we can do. I was thinking if we can disable some optional features from 3rd party crates that we don't use

**Comment by Stranger6667** [comment]
Yep, in our case, it improved the final size :) 

I took some ideas from [this](https://github.com/johnthagen/min-sized-rust) repo

> Something worth to notice is that thanks to LTO you can also strip part of the code that is not used (let's think about rayon does not include all the data-structures related to all the functional iterators)

Oh, that's cool :)

What do you think about using `strip` on the compiler libs?

**Comment by macisamuele** [comment]
I don't have a concrete idea yet, I'll be trying experimenting a bit.

Removing all symbols will definitely be good from a size perspective, I don't know if speed would change, but it would make harder to understand the issue if something fails on the rust side.

So my take here would be to compare the information that we might have in case of failure on rust (maybe inject a panic just for fun) in the two cases.

As far as shrinking the library as much as possible is good I think it might hit us back if then we're blind.

Note that using manylinix wheels over "normal" wheels already adds 1 or 2 MB into the wheel size

**Comment by Stranger6667** [comment]
I think we can close it after applying LTO & codegen-units=1 .

> As far as shrinking the library as much as possible is good I think it might hit us back if then we're blind.

I agree :)
