### ISSUE TITLE
Build wheels for other architectures

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#110]
- MacOs
- Windows 32bit
- Windows 64bit

**Comment by macisamuele** [comment]
If you don't mind I'd love to work on this as well as improving a bit the python infra (ie. Cargo.lock should be committed on the python project)

**Comment by Stranger6667** [comment]
Absolutely! FYI I took a lot from this repo when was doing Python CI - https://github.com/huggingface/tokenizers
