### ISSUE TITLE
Wheel publishing doesn't work on all platform

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#112]
Probably we need to have a previous version of that step for mac :(

https://github.com/Stranger6667/jsonschema-rs/runs/766075069?check_suite_focus=true#step:7:9

cc @macisamuele

**Comment by macisamuele** [comment]
@Stranger6667  thanks for pinging me on this.

This is ugly but I think that we can build all the wheels in parallel and then have a job that takes care only of publishing all the artifacts to pypi

Doing so would allow to have all-or-nothing published to pypi in case of transient failures which might be considered a benefit ;)

**Comment by Stranger6667** [comment]
> This is ugly but I think that we can build all the wheels in parallel and then have a job that takes care only of publishing all the artifacts to pypi

Sounds good to me! :)

**Comment by macisamuele** [comment]
One additional note https://github.com/Stranger6667/jsonschema-rs/runs/766075274?check_suite_focus=true

seems that `linux_x86_64` is not a platform accepted by pypi so we need to ensure that on linux we're publishing ONLY the manylinux wheel

**Comment by Stranger6667** [comment]
Yeah ... the older wheel should be removed / excluded from uploading.

https://github.com/Stranger6667/jsonschema-rs/runs/766075274?check_suite_focus=true#step:9:11

**Comment by Stranger6667** [comment]
Btw, when installing `sdist` package from pypi I faced with the following problem - `error: environment variable `OUT_DIR` not defined`

Should we have some fallback for such cases?

**Comment by macisamuele** [comment]
> Yeah ... the older wheel should be removed / excluded from uploading.

This surprise me as `linux_x86_64` should be a valid tag. But it's not a problem to remove it.

> when installing sdist package ...

I'm very surprised by it.

At this point I would say that the latest release is not really installable, so I would suggest to [yank it](https://pypi.org/help/#yanked) just to avoid issues ;)

I'll try to get back to you with this fix ASAP (expect a few hours as I need to get a walk after the working day 😎)

**Comment by macisamuele** [comment]
What I can say is that `OUT_DIR` variable is defined by the `build.rs` build script and is needed by `pyo3-built` to provide the metadata published in `jsonschema_rs.__build__`. 

Is that possible that it is not in the source binary?

I'm checking this idea
