### ISSUE TITLE
Include path/key in error message ?

### ISSUE THREAD

**Issue by yohanboniface** [Stranger6667/jsonschema-rs#144]
For example:

```python
import jsonschema_rs

validator = jsonschema_rs.JSONSchema({"type": "object", "properties": {"foo": {"type": "integer"}}})
validator.validate({"foo": None})
```

This will raise an error with the string `"'null' is not of type 'integer'"`. With a more complex schema, this message is not really helpful to understand what's wrong in the data. Is there a way to retrieve the property that hold that value ? Or maybe better a path to this property ?

I imagine something like this: `"path.to.foo: 'null' is not of type 'integer'"`

And it would be even better if the error instance would contain that path in a dedicated attribute, so one can format the message easily (say for example to return it in json).

Thanks :)

**Comment by Stranger6667** [comment]
Hi!

Indeed, it will be helpful! I think that #100  should cover it; however, I don't know when I will have the time for it :( PRs are welcome, though.

**Comment by yohanboniface** [comment]
For the record, another message that could be clearer:

```python
import jsonschema_rs

validator = jsonschema_rs.JSONSchema({"type": "object", "properties": {"foo": {"type": "integer"}}, "additionalProperties": False})
validator.validate({"bar": "baz"})
```

Error message will be `False schema does not allow '"bar"'`.

**Comment by wmain** [comment]
Big +1 to this issue. Without paths errors are essentially useless on schemas/data of our size.

**Comment by Stranger6667** [comment]
Hi, long overdue, but here are some updates for the most recent Rust version (changes were not released for Python bindings yet):

- Improved error message for the `additionalProperties` keyword: `Additional properties are not allowed ('bar' was unexpected)` which is similar to what Python's `jsonschema` is using;
- The `ValidationError` struct now has the `instance_path` attribute that could be treated as a JSON Pointer that erroneous part of the validated instance;

There are some complications on the Python side, though, as `PyO3` does not provide a way to customize exception types :( But they are solvable, and I'll post updates on that matter here.

**Comment by Stranger6667** [comment]
Here are few updates.

### New error messages include instance paths:

```
null is not of type "integer"

On instance["foo"]:
    null
```

Which is similar to what `jsonschema` is doing.

### Schema paths

Once #199 is ready, I'll expand the current error messages with schema paths.

### Separate attributes

Once `PyO3==0.14` is released (which should happen pretty soon), I'll add separate attributes for `instance_path` and `schema_path` (if it will be ready at that point).

**Comment by Stranger6667** [comment]
Starting from `0.11.1`, Python bindings additionally provide `message`, `schema_path` and `instance_path` attributes. The text representation is similar to `jsonschema`. For example:

```python
In [1]: import jsonschema
In [2]: jsonschema_rs.validate({"items": [{"type": "string"}]}, [1])
---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-4-252d7c044545> in <module>
----> 1 jsonschema_rs.validate({"items": [{"type": "string"}]}, [1])

ValidationError: 1 is not of type "string"

Failed validating "type" in schema["items"][0]["type"]

On instance[0]:
    1
```

`instance_path` is `[0]` and `schema_path` is `['items', 0, 'type']`. For the next step, I plan to add `schema` and `instance` attributes to `ValidationError`
