### ISSUE TITLE
Multi type: number/null type validation fails 

### ISSUE THREAD

**Issue by driv3r** [Stranger6667/jsonschema-rs#147]
Hi, I've encountered issue with validating numbers: example

Schema
```json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "content_length": {
            "type": ["number", "null"]
        }
    }
}
```

Object for test
```json
{
    "content_length": 42
}
```

when having those files under `benches/number_*` and running cli, I get

```
cargo run -- benches/number_schema.json -i benches/number_valid.json
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
     Running `target/debug/jsonschema benches/number_schema.json -i benches/number_valid.json`
benches/number_valid.json - INVALID. Errors:
1. '42' is not of types 'null', 'number'
```

But as far as I checked, this should be valid, at least by looking at https://github.com/Stranger6667/jsonschema-rs/blob/master/src/keywords/type_.rs#L54-L57 with my beginners rust knowledge.

Also when running against `"type":["number"]` everything looks as it's supposed to.

**Comment by Stranger6667** [comment]
Hi! Thanks for reporting, I'll take a look :)

**Comment by Stranger6667** [comment]
Yes, it is a bug; the upstream test suite (at least the version used by this lib) does not include such cases. I'll work on a fix

**Comment by driv3r** [comment]
@Stranger6667 this was fast! Kudos!

**Comment by Stranger6667** [comment]
@driv3r You're welcome! I will release the fix tomorrow :)

**Comment by Stranger6667** [comment]
FYI @driv3r . There are still some issues regarding the comparison of two JSON values (#149) - but I plan to release a fix for this one and then make some refactorings & solve #148 in subsequent patches
