### ISSUE TITLE
Use the original value in error formatting for some numeric validators

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#215]
Validating `3.0` against `{"exclusiveMaximum": 3.0}` will give `3.0 is greater than or equal to the maximum of 3`. But the last number in the error message should be `3.0`. It affects `exclusiveMaximum`, `exclusiveMinimum`, `minimum`, `maximum`.

**Comment by djmitche** [comment]
I'll give this a shot, if that's OK :)

**Comment by Stranger6667** [comment]
@djmitche 
Absolutely :) Thank you

Let me know if I can help

**Comment by djmitche** [comment]
It looks like this would be passing a different value for `limit` in `src/keywords/exclusive_maximum.rs` (and similarly for the other limits).  Two questions:

 * For f64, this will mean printing a parsed value that may not match the source document (e.g., `3.0000` -> `3.0`).  I think that's the best we can do, given a `json::Value` in the schema.  Is that OK?
 * Presently, the `limit` parameter is an f64, I think as a way of encompassing all possible values.  Would it make most sense to switch this to a string, and stringify when creating the error?  Or should I carry the `Value`-typed limit all the way through, and pass that to the error constructor?  ("Should" in the sense of, what best matches the approach taken elsewhere in this codebase)

**Comment by djmitche** [comment]
Well, I [gave that a try](https://github.com/Stranger6667/jsonschema-rs/compare/master...djmitche:issue215?expand=1) and it didn't work out too well:

```
thread 'error::tests::limit_error_display::_number_from_f64_3_0_unwrap_3_0_' panicked at 'assertion failed: `(left == right)`
  left: `"42 is greater than or equal to the maximum of 3"`,
 right: `"42 is greater than or equal to the maximum of 3.0"`', src/error.rs:1023:9
```

it turns out `Number` (which is what I meant when I wrote `Value` above) is "smart' about formatting whole numbers.  Digging in, it looks like `Display::fmt(&f64, ..)` is smart about this.  It looks like `impl Display for Value` handles this by re-serializing the value, and gets the `.0`.  So perhaps I just need to use `{:?}` to print the limit, or perhaps I need to pass the full `Value` after all..

**Comment by djmitche** [comment]
OK, [this](https://github.com/Stranger6667/jsonschema-rs/compare/master...djmitche:issue215?expand=1) passes the updated tests; it keeps a `limit_val` as a means to reconstitute the limit representation.  If this is OK with you, I'll do the same for the other limits.

**Comment by Stranger6667** [comment]
Yep, I believe that passing `Value` is the way to go - this approach is already used in `enum`. I hope that it answers the questions above :) I like the code you shared, so I'd be delighted to have a PR with it :)

Thank you

**Comment by Stranger6667** [comment]
Fixed by #275

Thanks @djmitche :)

**Comment by djmitche** [comment]
While I have you, I noticed at the *bottom* of the README it says this is in early development.  Is that still the case?

**Comment by Stranger6667** [comment]
I think it is not in early development anymore, but the library is at `0.x` versions as I think that its API is still shaping.
