### ISSUE TITLE
WASM bindings

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#222]

**Comment by islami00** [comment]
Hi, 

I'd like to know the requirements for this issue to be completed so I could give it a try as I intend to perform jsonschema validation in a wasm environment an this package would be very helpful in that.

**Comment by oovm** [comment]
```sh
   Compiling jsonschema v0.16.0
error[E0433]: failed to resolve: could not find `blocking` in `reqwest`
  --> github.com-1ecc6299db9ec823\jsonschema-0.16.0\src\resolver.rs:85:45
   |
85 |                     let response = reqwest::blocking::get(url.as_str())?;
   |                                             ^^^^^^^^ could not find `blocking` in `reqwest`

error[E0599]: no method named `to_file_path` found for reference `&Url` in the current scope
  --> github.com-1ecc6299db9ec823\jsonschema-0.16.0\src\resolver.rs:95:43
   |
95 |                     if let Ok(path) = url.to_file_path() {
   |                                           ^^^^^^^^^^^^ method not found in `&Url`

Some errors have detailed explanations: E0433, E0599.
For more information about an error, try `rustc --explain E0433`.
error: could not compile `jsonschema` due to 2 previous errors
```

**Comment by manuschillerdev** [comment]
It would be really powerful to have your json-schema validator available in wasm!

**Comment by Niraj-Kamdar** [comment]
@Stranger6667 It can compile to wasm if you disable the default-feature and only enable `structopt` in the `Cargo.toml`

```
jsonschema = { version = "=0.15.0", default-features = false, features = ["structopt"]}
```

pure wasm doesn't support IO natively so if we want to add support for the IO ref-resolver then we need to provide custom bindings for that or use WASI if runtime supports that. 

> I was able to compile it down to the wasm module with the above configuration, I didn't need to parse IO refs so It worked for me.

**Comment by Stranger6667** [comment]
Closing in favor of #568 Right now `jsonschema` runs tests on `wasm32-wasip1` in CI, and provides some error messages specifically for wasm + there is a docs section about it. 

Later on, I'll add JS bindings to use it in a browser (and a demo website!), but that is a separate thing and I'll create a new issue for it.

**Comment by postsql** [comment]
> "+ there is a docs section about it."

Can you give a link to this doc section ?

Search for "wasm" in  https://docs.rs/jsonschema/latest/jsonschema/ returned nothing and also grep in this source did not anything looking like docs for compiling to WASM

**Comment by Stranger6667** [comment]
Hey! I haven’t release it yet, you can check it here now - https://github.com/Stranger6667/jsonschema-rs/blob/6b934d55553af4b34340be8e6604fc87c8d70e4b/crates/jsonschema/src/lib.rs#L451

let me know if the section is not enough, I’m happy to expand it
