### ISSUE TITLE
[Question] How to parse without validating

### ISSUE THREAD

**Issue by yordis** [Stranger6667/jsonschema-rs#238]
Hey there,

First, I am new to Rust so my apologies if I am asking basic questions.

I am wondering if you a function that just parses the schema definition without running validations. My intention is to use this package to generate TypeScript types from a jsonschema, so having reach objects is helpful (also without dropping extension values)

**Comment by Stranger6667** [comment]
Hi @yordis !

This library doesn't do parsing itself (except the conversion logic in Python bindings), only validation. It is done by `serde_json` - it will provide you with `serde_json::Value` values that will represent the input structure. 

If you need some precise types for JSON Schema (e.g. a type for `Minimum` keyword or separate attribute for `description` keywords), then this library does not provide any, as its internals are optimized for performance purposes and store only things needed for validation in a "compiled" state (some things could be pre-computed).
