### ISSUE TITLE
Consider collecting all errors without intermediate iterators

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#251]
The current implementation is not really lazy on nesting levels deeper than the root one - the errors are collected into vectors and then returned as iterators. It might be much simpler to pass a mutable ref to a vector of errors into each `validate` and do not return anything from those methods. There will be no `collect` calls, and no boxes to return from `validate`.

I am not sure whether it is actually possible to implement a completely lazy validation without generators or building a state machine.

**Comment by colbyn** [comment]
For me the choice of returning an iterator isn't significant, the real problem I have is that the returned error types include lifetimes in the data structure itself which makes it impossible to use in an owned context.

**Comment by Stranger6667** [comment]
I'll gather all the improvement ideas about errors in #114 (including the one in the comment above)
