### ISSUE TITLE
Option to turn off processing of the `format` keyword

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#261]
From the Draft 2019-09 [release notes](https://json-schema.org/draft/2019-09/release-notes.html):

> The key difference here is that format validation is now predictably off by default, but can be configured to be turned on. In draft-07, it was on (but possibly unimplemented) by default and could be configured to be turned off.

The release notes page contains a table with possible validation outcomes, depending on multiple factors - `support level`, `configuration`, and `vocabulary`. In our case, we don't support vocabularies just yet and I don't see much reason to distinguish "full syntax" vs "best effort" support level, so I think we can reduce that table to this one:

| supported        | configuration           | outcome  |
| -------------: | -------------:| -----:|
| no      | - | not validated |
| yes      | default (off) | not validated |
| yes      | on | validated |

When vocabularies will be implemented, we can revisit this behavior and add some `VocabularyError` to the mix.

On the implementation side, it can be controlled with a new configuration value in `compilation::options::CompilationOptions` that will turn format validation on and off (with `false` as the default value in `Default` impl). Let's say it is `validate_formats`, then its value is `false` on the new draft (which is behind a feature flag at the moment) and `true` on older drafts to maintain backward-compatible behavior.

This change will require a setter on `compilation::options::CompilationOptions` similarly to other setters there.
Then, depending on this value we can just return `None` from `keywords::format::compile` if it is `false`, which will turn format validation off.

**Comment by oren0e** [comment]
Any details regarding this? I might try to do it

**Comment by Stranger6667** [comment]
@oren0e 

Thanks!

I updated the issue description :) Let me know if it provides enough details, I'll be happy to elaborate if it doesn't
