### ISSUE TITLE
Reduce the size of `PrimitiveTypesBitMapIterator`

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#282]
Now it is [3 bytes](https://github.com/Stranger6667/jsonschema-rs/blob/master/jsonschema/src/primitive_type.rs#L139), but can be two bytes if instead of range there will be `u8` as an index. The iterator is only used in validators' `Display` and in `ValidationError` display, so the impact is quite small

**Comment by plaxi0s** [comment]
Hi, I tried to fix this in #292. Please do share your views. 
Thanks!

**Comment by Stranger6667** [comment]
Closed via #292 
Thanks @plaxi0s
