### ISSUE TITLE
Implement `unevaluatedItems`

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#287]
[Example implementation](https://github.com/python-jsonschema/jsonschema/blob/main/jsonschema/_keywords.py#L392) in Python. [Docs](https://datatracker.ietf.org/doc/html/draft-bhutton-json-schema-00#section-11.2)

**Comment by sarthakjalan05** [comment]
@Stranger6667 assign me this task under the hacktoberfest tag!!!
