### ISSUE TITLE
Python interface

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#30]
PyO3

As proposed by @macisamuele , this library might help - https://github.com/macisamuele/json-trait-rs

CFFI implementation that I started is far from being done, there are some weird edge cases that I don't know how to handle. E.g. calling `PyLong_FromLongLong` on a big integer produces more corruption :/

**Comment by macisamuele** [comment]
@Stranger6667 I'll try to update all the keywords in order to allow validation of a generic JsonType. I'll try to compare it with the benchmarks to identify possible regressions or additional issues

**Comment by Stranger6667** [comment]
Do you mean non-serde types?

**Comment by macisamuele** [comment]
Ideally (at least this what I was experimenting with) the `Validate` trait should be modified into something like
```rust
trait Validate<J: JsonType> {
    fn validate(&self, schema: JsonSchema<J>, value: &J) -> ...;
    fn is_valid(&self, schema: JsonSchema<J>, value: &J) -> bool;
}
```
By doing so we might validate for any type `J` that implements `JsonType` trait.

If by doing it we don't introduce performance regressions then we might simplify the integration with foreign platforms (which might be Python or any other FFI) that adhere to `JsonType` trait.

Still this is a very preliminary idea, as I need to finalise the test branch to see the feasibility (especially comparing performances).

Once I have results (maybe over the weekend) I'll post something in here.

**Comment by Stranger6667** [comment]
Done in #54.

Sdist & wheels for manylinux2010 are [here](https://pypi.org/project/jsonschema-rs/#files)
