### ISSUE TITLE
Python enum validation

### ISSUE THREAD

**Issue by blacha** [Stranger6667/jsonschema-rs#316]
Hi @Stranger6667, Another issue that I'm running into is with Python `enum`'s

Given the following piece of code by default the `Enum` is not converted to a string

```python
from jsonschema_rs import is_valid
import orjson

from enum import Enum

class Foo(Enum):
   bar = "bar"
   foo = "foo"

schema = {"properties": {"foo": {"type": "string"}}}
instance = {"foo": Foo.bar}

converted = orjson.loads(orjson.dumps(instance))
print(is_valid(schema, converted)) # True

print(is_valid(schema, instance)) # ValueError: Unsupported type: 'Foo'
```

I am thinking of two options and wondering which you would prefer

1. Automatically converting Enums to their corresponding type (str, int, etc) like how orjson does it
2. Creating a `string` based interface `validate_str(orjson.dumps(instance))` 

I like the simplicity of 1 for the end user as they don't have to worry about converting their enum's with `Foo.bar.value` before validating.

**Comment by Stranger6667** [comment]
Hi!

I think for this exact use case, option number one is the way to go. 

However, the second option might also be useful in some circumstances. It would be convenient to have it in web apps, where the value is available as raw request payload (`str` / `bytes`). In this case, the user might use the raw payload to validate the data before parsing it on the Python level (though, the parsing process will happen two times). But in some cases like forwarding the payload to another app, parsing on the Python level might not be needed at all, so it would be useful there.
