### ISSUE TITLE
Set `default-features = false` for reqwest dependency

### ISSUE THREAD

**Issue by jqnatividad** [Stranger6667/jsonschema-rs#335]
First, thanks @Stranger6667 for this amazing library as it allows [qsv](https://github.com/jqnatividad/qsv) to validate CSVs.

However, we're having difficulty building binaries using cross as the reqwest dependency brings in native-tls by default, which in turn pulls in openssl which is no longer supported by cross (https://github.com/rust-embedded/cross/issues/229), even if I take advantage of the jsonschema's reqwest-rustls-tls feature.

Would it be possible to set `default-features = false` in the reqwest dependency? 

In that way, jsonschema users can specify which tls they want to use and the reqwest dependency forwarding feature actually works as expected.

**Comment by Stranger6667** [comment]
Hi @jqnatividad 

Glad you find the library helpful :) Thank you for opening this issue, sure, the proposed change makes complete sense and I'll take a look at #336 shortly

**Comment by Stranger6667** [comment]
Released in `0.14.0` :)
