### ISSUE TITLE
Library cannot be build with `minimal-versions`

### ISSUE THREAD

**Issue by fujiapple852** [Stranger6667/jsonschema-rs#346]
As of the latest master (https://github.com/Stranger6667/jsonschema-rs/commit/778b424b3de65f2ed6df64a2558bde7341c0094b) the library does not compile with cargo `minimal-versions` for the default features:

```shell
cargo +nightly update -Z minimal-versions && cargo +nightly check
```

Resolved in https://github.com/Stranger6667/jsonschema-rs/pull/345

**Comment by Stranger6667** [comment]
Resolved in #345 

Thanks!
