### ISSUE TITLE
reqwest is not optional with version 0.15.2 ?

### ISSUE THREAD

**Issue by samueldotj** [Stranger6667/jsonschema-rs#359]
I am trying to compile without reqwest(which has lot of dependency) and this the following code breaks the compilation.

https://github.com/Stranger6667/jsonschema-rs/blob/e2d09aa932145db970556eb1fe1ed6edb824a270/jsonschema/src/resolver.rs#L78-L90

`rust-v0.15.1` tag does not have this problem.

**Comment by silverjam** [comment]
We seem to be experiencing this too

![image (1)](https://user-images.githubusercontent.com/183436/164283530-a32b32a3-c81b-4ada-b81a-2358adfa9648.png)

**Comment by Stranger6667** [comment]
Hi @samueldotj @silverjam 

Sorry for the complication, I'll resolve it soon.

**Comment by silverjam** [comment]
> Hi @samueldotj @silverjam 
> 
> 
> 
> Sorry for the complication, I'll resolve it soon.

Thank you!
