### ISSUE TITLE
ERROR: Failed building wheel for jsonschema_rs on Python 3.10 on Windows

### ISSUE THREAD

**Issue by karolzlot** [Stranger6667/jsonschema-rs#369]
On 3.9 it works fine.

**Comment by Stranger6667** [comment]
Hi!

Could you, please share your error log? 

I didn't issue a new release where `PyO3` dependency was updated, but as far as I can see, the `PyO3` version that is used in the latest `jsonschema_rs` version supports Python 3.10.

**Comment by Stranger6667** [comment]
The new version comes with wheels for Windows 64bit/ CPython 3.10. Let me know if it works for you

**Comment by karolzlot** [comment]
I confirm it now works ok on Python 3.10:

```
Successfully installed jsonschema_rs-0.16.0
```

**Comment by Stranger6667** [comment]
Awesome!
