### ISSUE TITLE
http and file resolver should be added via optional features 

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Stranger6667/jsonschema-rs#395]
Currently, jsonschema lib can't be compiled down to a wasm module since it relies on HTTP and File IO which aren't supported by the WASM standard. 

It'd be better to allow users to add the ref resolver module as an optional feature.
`jsonschema = { version = "0.16.0", features = ["ref-resolver"]}`

**Comment by Stranger6667** [comment]
Are the `resolve-http` and `resolve-file` features not sufficient for this?

**Comment by Niraj-Kamdar** [comment]
@Stranger6667 Oops missed it! Yeah disabling those would totally work.

**Comment by Stranger6667** [comment]
Great to hear! :) I'd like to have `jsonschema` compiled to WASM eventually

Related: #222
