### ISSUE TITLE
Try compile tauri in wasm target , encountered some problems

### ISSUE THREAD

**Issue by tu6ge** [Stranger6667/jsonschema-rs#400]
Hi, First of all, I'm not the maintainer of tauri. 

I find the `tauri-cli` crate used  jsonschema, and I am trying run it with wasm , When I run [here](https://github.com/Stranger6667/jsonschema-rs/blob/master/jsonschema/src/resolver.rs#L95), an error is reported.

so, I changed it like [this](https://github.com/Stranger6667/jsonschema-rs/compare/master...tu6ge:jsonschema-rs:master), Because tauri does not use this part when parsing json. From the perspective of jsonschema, this change should be inappropriate. Is there a more reasonable solution ?

**Comment by Stranger6667** [comment]
Sorry for not responding here in almost 2 years ... Closing this issue in favor of #568 which I gathered all the steps needed to improve the usage of `jsonschema` in WASM (it could be used right now, but requires some better docs & guidance)
