### ISSUE TITLE
Schema with pattern re-compute regexp on each validate call 

### ISSUE THREAD

**Issue by ermakov-oleg** [Stranger6667/jsonschema-rs#416]
Example schema:
```
{'pattern': '^(foo|bar)$', 'format': 'regex', 'type': 'string'}
```
https://github.com/Stranger6667/jsonschema-rs/blob/master/jsonschema/src/keywords/format.rs#L284-L294

**Comment by Stranger6667** [comment]
The ‘pattern’ keyword is not relevant here as the mentioned code is only for ‘format’, but indeed it verifies correctness of the input regex by trying to compile it. Not sure whether we can do anything about it besides adding some cache for inputs (but it is a a more broad issue for any validator)

**Comment by Stranger6667** [comment]
Is caching for input strings something that you were thinking about?

**Comment by Stranger6667** [comment]
I guess it could be nice to have a global cache for it - as format is universal and all ‘regex’ format validators could utilise it

**Comment by ermakov-oleg** [comment]
Hmm, really, if you don't specify "format", regexp caches fine. 
Then it's just not very expected behavior...

**Comment by ermakov-oleg** [comment]
Oh, really, I misunderstood the specification...
Sorry if I distracted you. I will close this issue.

**Comment by Stranger6667** [comment]
No worries at all! On the contrary - I think it actually an interesting opportunity to explore caching possibilities for the “pattern” format
