### ISSUE TITLE
`JSONSchema` and `JSONPointer` don’t follow naming conventions

### ISSUE THREAD

**Issue by SabrinaJewson** [Stranger6667/jsonschema-rs#424]
See [C-CASE](https://rust-lang.github.io/api-guidelines/naming.html#casing-conforms-to-rfc-430-c-case):

> In `UpperCamelCase`, acronyms and contractions of compound words count as one word: use `Uuid` rather than `UUID`, `Usize` rather than `USize` or `Stdin` rather than `StdIn`

These types should be named `JsonSchema` and `JsonPointer`.

(this is quite low-priority but you might want to fix it before 1.0)

**Comment by Stranger6667** [comment]
Thank you for opening this issue! I was thinking about it and the main concern was the name clash with ‘schemars’, so I put all the renaming things aside. However, I’d like to address it before 1.0
