### ISSUE TITLE
`Error: Error("expected ident", line: 1, column: 2)` when running from command line

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [Stranger6667/jsonschema-rs#428]
- `cargo install jsonschema`
- `jsonschema -i ./specs/android/adb_root_emulator.yaml ./schemas/workflow.json`, where:
  - adb_root_emulator.yaml is defined [here](https://github.com/warpdotdev/workflows/blob/main/specs/android/adb_root_emulator.yaml)
  - workflow.json is defined [here](https://github.com/warpdotdev/workflows/pull/159/files#diff-688542d3e1b371b39f7dfbc9233c13db4f0e3a1610b20f6cf7d1b8336e5100fe)
- get error `Error: Error("expected ident", line: 1, column: 2)`

**Comment by Stranger6667** [comment]
So sorry for the delay! JSON Schema CLI does not support YAML, hence the error. I'll update the docs
