### ISSUE TITLE
Get line column of error

### ISSUE THREAD

**Issue by JMarkin** [Stranger6667/jsonschema-rs#440]
Hello, How can I get json position(column line?) of error ?

**Comment by Stranger6667** [comment]
So sorry for the delay!

`jsonschema` does not track such information as it works with `serde_json::Value` which does not contain such information. I.e. this crate works on the semantic level, but column & line info is only available during parsing (with `serde_json` at least).

However, with `instance_path` it should be possible to implement such a feature separately as it ultimately shows the location within the document.
