### ISSUE TITLE
Under what circumstances will jsonschema make network requests?

### ISSUE THREAD

**Issue by bsl** [Stranger6667/jsonschema-rs#449]
Is it true that jsonschema will only (possibly) make network requests during schema compilation?
Is it true that jsonschema will never make network requests based on anything it is being asked to validate?

**Comment by Stranger6667** [comment]
Hey @bsl !

This crate does resolving during the validation phase, even though I'd like to eventually move it to the compilation phase. But it also can be avoided by disabling the `resolve-http` feature - it will lead to a runtime error if a remote ref occurs during the validation process. 

Hopefully, it clarifies the state of things. But I'd like to note, that eventually, I'd like to move all network calls to the compilation phase and avoid them during validation altogether.
