### ISSUE TITLE
Only enabling `draft202012` features misses some features implemented only for `draft201909`

### ISSUE THREAD

**Issue by jrudolph** [Stranger6667/jsonschema-rs#456]
In my case, it was the `uuid` format validator that is only available when `draft201909` is enabled.

One possibility could be to include the full `draft201909` feature in `draft202012` in cargo.toml.

Alternatively, if draft202012 is not a strict superset of draft201909, the conditional compilation should be changed in a way that all json schema features that are both in draft202012 and draft201909 are also enabled if only the draft202012 is selected.

I can open a PR if we can agree on which way to go.

Thanks for this nice library!

**Comment by Stranger6667** [comment]
Sorry for the delay! `uuid` fix landed recently and will be available in the next release
