### ISSUE TITLE
How do I resolve an external schema?

### ISSUE THREAD

**Issue by TianzeMYou** [Stranger6667/jsonschema-rs#469]
I tried looking for examples but I can't seem to figure out how to use the resolver (I am quite new at Rust).
According to this API https://docs.rs/jsonschema/0.17.1/jsonschema/trait.SchemaResolver.html should I do
`use jsonschema::[SchemaResolver]`?

What next? How is SchemaResolver related to resolve-http or resolve-file?

**Comment by Stranger6667** [comment]
Meanwhile, I've added a separate section about reference resolving and I hope it should cover everything in detail :) Don't hesitate to ask more questions and I'm sorry for responding so long.

https://docs.rs/jsonschema/0.22.3/jsonschema/#external-references
