### ISSUE TITLE
Cannot obtain `String` from `ErrorDescription`

### ISSUE THREAD

**Issue by matteopolak** [Stranger6667/jsonschema-rs#488]
Hey there! I'm looking to obtain ownership over the `String` contained within `ErrorDescription`, but the only way I can see that being possible is cloning the string (via its `Display` impl), which isn't great since I already have ownership of the `ErrorDescription`.

Is there another way to do it that I'm missing? I was hoping for e.g. `ErrorDescription::into_inner`, or for the field to be `pub`

I can PR this if it sounds like something you'd consider adding to the library.

**Comment by Stranger6667** [comment]
Hi! Yes, `into_inner` sounds good to me!

**Comment by matteopolak** [comment]
Great! Created #492 to resolve this.
