### ISSUE TITLE
`ValidationError` Fns are mostly pub(crate)

### ISSUE THREAD

**Issue by jqnatividad** [Stranger6667/jsonschema-rs#490]
which prevents me from using them apart from `ValidationError::custom()` when trying to make custom validators.

**Comment by Stranger6667** [comment]
Oh, my thinking was that the only public-facing function would be `custom`, but it indeed looks more flexible to have more constructors public. Could you, please, share your use case?

**Comment by jqnatividad** [comment]
Never mind @Stranger6667 . It turns out I only needed `custom`.

Check out the new `dynenum` custom keyword in qsv! 😄 

https://github.com/jqnatividad/qsv/commit/cd4ec1264db895414f5da3abf26d807079eb2c2b

**Comment by Stranger6667** [comment]
Thank you for sharing! :) Really cool!

Somewhere in October/November I plan to rework the error handling so it is possible to do more customization with the error messages and I'll surely take a look back and try to improve the ergonomics
