### ISSUE TITLE
Provide explanation in errors when the input schema is not valid

### ISSUE THREAD

**Issue by Stranger6667** [Stranger6667/jsonschema-rs#57]
At the moment it is only `Schema compilation error`

**Comment by Stranger6667** [comment]
If we'll have a metaschema validation, then this will be covered. Details are in #28

**Comment by nokome** [comment]
Thanks for `jsonschema` :pray:. I've just started using it, so perhaps a noob question...

With `0.6.0` I'm still only getting the error message `Schema compilation error` when using `JSONSchema::compile(&schema)` or `JSONSchema::options().with_meta_schemas().compile(&schema)`. Should I be doing something different, or does this require #100 to be completed?

**Comment by Stranger6667** [comment]
Hi @nokome 

Sorry for the late reply! This problem went out of my scope and I think that it is separate - #100 will provide better error messages for sure, but at the moment meta schemas are only stored and not used for validation. I think that instead of `CompilationError` and `ErrorIterator` we can only have the latter and have it as the `Err` variant for the `JSONSchema::compile` return type.

**Comment by Stranger6667** [comment]
Closed in favor of #198

**Comment by Stranger6667** [comment]
@nokome

FYI - as #198 is merged and released, schema errors are reported in the same fashion as validation errors. There is an error message & `instance_path`  that may help with debugging
